### ISSUE TITLE
Build fails with jekyll 3.8.3 | Error:  undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by Rocketpilot** [calebhicks/jekyll-airtable-utilities#1]
This tool looks ideal for my needs but I am having trouble getting it to work.

I'm starting from a clean install of Jekyll with your plugins added.

When I `bundle exec jekyll serve`, airtable_fetch does not seem to work. It fails with 

```ruby
Error:  undefined method `each' for nil:NilClass
```

I'm not really a programmer but it seems like 

```ruby
table['sheets'].each do |sheet|
```

Is where it goes wrong. I have output the contents of `@airtable_config['tables']` and that seems fine? 

I have tried a number of alterations to the config file and I currently have it set at

```yaml
airtable:
    api_key: MY_API_KEY
    tables:
        -
            name: Painting Checklist
            app_id: MY_APP_ID
            sheets: [{name: Paints, view: Grid view}]
        -
            name: Painting Checklist
            app_id: MY_APP_ID
            sheets: [{name: Paint Manufacturer, view: Grid view}]
```

But I have tried other combinations, like the set name for each view, and nothing works.

Any suggestions?
